import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/queryClient";
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider> 
    <html lang="en">
      <body
      className="min-h-screen flex"    
      >
        {children}
        <Toaster  position="bottom-center" />
      </body>
    </html>
    </QueryProvider>
  );
}
